-- migrate:up

CREATE SCHEMA IF NOT EXISTS moneyman;

-- Enums
CREATE TYPE moneyman.cash_flow_type AS ENUM (
    'salary',
    'other_income',
    'expense',
    'savings',
    'internal_transfer'
);

CREATE TYPE moneyman.investment_account_type AS ENUM (
    'חשבון השקעות פרטי',
    'קרן השתלמות',
    'פק"מ',
    'קרן כספית',
    'קרן פנסיה מקיפה',
    'קרן פנסיה משלימה',
    'ביטוח מנהלים',
    'קופת גמל',
    'עובר ושב',
    'חסכון לכל ילד',
    'קופת גמל להשקעה'
);

-- Auto-imported bank/CC transactions (written by moneyman)
CREATE TABLE moneyman.transactions (
    unique_id         text                        NOT NULL,
    company_id        text                        NOT NULL,
    account           text                        NOT NULL,
    status            text                        NOT NULL,
    activity_date     date                        NOT NULL,
    charged_amount    numeric                     NOT NULL,
    charged_currency  text,
    original_amount   numeric,
    original_currency text,
    description       text,
    memo              text,
    identifier        text,
    installments      jsonb,
    raw               jsonb                       NOT NULL,
    created_at        timestamp with time zone    DEFAULT now() NOT NULL,
    updated_at        timestamp with time zone    DEFAULT now() NOT NULL,
    CONSTRAINT transactions_pkey PRIMARY KEY (unique_id)
);

CREATE INDEX transactions_company_account_date_idx
    ON moneyman.transactions USING btree (company_id, account, activity_date);

-- Manually entered transactions and income
CREATE TABLE moneyman.transactions_manual (
    unique_id           text                        NOT NULL,
    account             text,
    activity_date       date,
    description         text,
    original_amount     numeric,
    original_currency   text,
    charged_amount      numeric,
    charged_currency    text,
    identifier          text,
    additional_info     text,
    charged_date        timestamp without time zone,
    created_at          timestamp with time zone,
    updated_at          timestamp with time zone,
    show_in_transactions boolean                    DEFAULT true,
    cash_flow_type      moneyman.cash_flow_type     DEFAULT 'expense'::moneyman.cash_flow_type,
    CONSTRAINT transactions_manual_pk PRIMARY KEY (unique_id)
);

-- Raw JSON payloads from moneyman (archive/debugging)
CREATE TABLE moneyman.transactions_raw (
    id         bigint                      NOT NULL,
    raw        jsonb                       NOT NULL,
    created_at timestamp with time zone   DEFAULT now() NOT NULL,
    CONSTRAINT transactions_raw_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE moneyman.transactions_raw_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE moneyman.transactions_raw_id_seq OWNED BY moneyman.transactions_raw.id;
ALTER TABLE ONLY moneyman.transactions_raw
    ALTER COLUMN id SET DEFAULT nextval('moneyman.transactions_raw_id_seq'::regclass);

-- User-defined category mappings (description → category/subcategory)
CREATE TABLE moneyman.description_to_category (
    id          integer GENERATED BY DEFAULT AS IDENTITY (
                    SEQUENCE NAME moneyman.description_to_category_id_seq
                    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
                ) NOT NULL,
    description text,
    category    text,
    subcategory text,
    CONSTRAINT description_to_category_pkey PRIMARY KEY (id)
);

-- Canonical business names (e.g. "Wolt - Place A" → "Restaurant X")
CREATE TABLE moneyman.business_descriptions (
    id          integer GENERATED BY DEFAULT AS IDENTITY (
                    SEQUENCE NAME moneyman.wolt_descriptions_id_seq
                    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
                ) NOT NULL,
    description character varying,
    CONSTRAINT wolt_descriptions_pk PRIMARY KEY (id)
);

-- Maps transaction unique_ids to a canonical business name
CREATE TABLE moneyman.business_transaction_mappings (
    unique_id               text    NOT NULL,
    business_descriptions_id integer,
    CONSTRAINT wolt_transactions_mappings_pk PRIMARY KEY (unique_id),
    CONSTRAINT wolt_transactions_mappings_wolt_descriptions_fk
        FOREIGN KEY (business_descriptions_id)
        REFERENCES moneyman.business_descriptions(id)
);

-- Monthly aggregated income/expense/savings per person and account
CREATE TABLE moneyman.monthly_cash_flow (
    year              integer,
    month             integer,
    person            character varying(50),
    account           character varying(50),
    income            numeric,
    expense           numeric,
    money_transferred numeric,
    savings           numeric,
    comments          text
);

-- Investment account metadata (one row per account)
CREATE TABLE moneyman.investment_accounts (
    id                      integer                             NOT NULL,
    person                  text                                NOT NULL,
    company                 text                                NOT NULL,
    account_type            moneyman.investment_account_type    NOT NULL,
    account_type_category   text,
    is_active               boolean                             DEFAULT true NOT NULL,
    is_pension              boolean                             DEFAULT false NOT NULL,
    deposit_management_fees numeric,
    acc_management_fees     numeric,
    investment_track        text,
    monthly_deposit         numeric,
    account_number          text,
    CONSTRAINT investment_accounts_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE moneyman.investment_accounts_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE moneyman.investment_accounts_id_seq OWNED BY moneyman.investment_accounts.id;
ALTER TABLE ONLY moneyman.investment_accounts
    ALTER COLUMN id SET DEFAULT nextval('moneyman.investment_accounts_id_seq'::regclass);

-- Periodic valuations of each investment account
CREATE TABLE moneyman.investment_accounts_tracking (
    id                      integer NOT NULL,
    investment_accounts_id  integer NOT NULL,
    activity_date           date    NOT NULL,
    amount                  numeric NOT NULL,
    CONSTRAINT investment_accounts_tracking_pkey PRIMARY KEY (id),
    CONSTRAINT investment_accounts_tracking_investment_accounts_id_fkey
        FOREIGN KEY (investment_accounts_id) REFERENCES moneyman.investment_accounts(id)
);

CREATE SEQUENCE moneyman.investment_accounts_tracking_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE moneyman.investment_accounts_tracking_id_seq
    OWNED BY moneyman.investment_accounts_tracking.id;
ALTER TABLE ONLY moneyman.investment_accounts_tracking
    ALTER COLUMN id SET DEFAULT nextval('moneyman.investment_accounts_tracking_id_seq'::regclass);

-- View: unified transactions from both sources (negates manual amounts to match transactions sign convention)
CREATE VIEW moneyman.combined_transactions AS
    SELECT t.unique_id, t.company_id, t.account, t.status, t.activity_date,
           t.charged_amount, t.charged_currency, t.original_amount, t.original_currency,
           t.description, t.memo, t.identifier, t.installments, t.raw, t.created_at, t.updated_at
      FROM moneyman.transactions t
    UNION
    SELECT tm.unique_id, NULL::text AS company_id, tm.account, NULL::text AS status,
           tm.activity_date, (('-1'::integer)::numeric * tm.charged_amount) AS charged_amount,
           tm.charged_currency, tm.original_amount, tm.original_currency, tm.description,
           NULL::text AS memo, tm.identifier, NULL::jsonb AS installments, NULL::jsonb AS raw,
           tm.created_at, tm.updated_at
      FROM moneyman.transactions_manual tm
     WHERE tm.show_in_transactions IS TRUE;

-- View: business transaction mappings joined with their canonical descriptions
CREATE VIEW moneyman.wolt_transactions_all_info AS
    SELECT wtm.unique_id,
           wtm.business_descriptions_id AS wolt_descriptions_id,
           wd.description AS mapped_description
      FROM moneyman.business_transaction_mappings wtm
      LEFT JOIN moneyman.business_descriptions wd ON wtm.business_descriptions_id = wd.id;

-- View: all transactions enriched with category mappings and resolved business names
-- charged_amount is negated here so positive = expense (bank sign convention reversal)
CREATE VIEW moneyman.processed_transcations_with_categories AS
    SELECT t.unique_id, t.company_id, t.account, t.status, t.activity_date,
           (('-1'::integer)::numeric * t.charged_amount) AS charged_amount,
           t.charged_amount AS orignial_charged_amount,
           t.charged_currency, t.original_amount, t.original_currency, t.description,
           COALESCE(w.mapped_description, t.description::character varying) AS processed_description,
           dtc.category, dtc.subcategory,
           t.memo, t.identifier, t.installments, t.created_at, t.updated_at
      FROM moneyman.combined_transactions t
      LEFT JOIN moneyman.wolt_transactions_all_info w ON t.unique_id = w.unique_id
      LEFT JOIN moneyman.description_to_category dtc
             ON COALESCE(w.mapped_description, t.description::character varying)::text = dtc.description;


-- migrate:down

DROP VIEW IF EXISTS moneyman.processed_transcations_with_categories;
DROP VIEW IF EXISTS moneyman.wolt_transactions_all_info;
DROP VIEW IF EXISTS moneyman.combined_transactions;
DROP TABLE IF EXISTS moneyman.investment_accounts_tracking;
DROP TABLE IF EXISTS moneyman.investment_accounts;
DROP TABLE IF EXISTS moneyman.monthly_cash_flow;
DROP TABLE IF EXISTS moneyman.business_transaction_mappings;
DROP TABLE IF EXISTS moneyman.business_descriptions;
DROP TABLE IF EXISTS moneyman.description_to_category;
DROP TABLE IF EXISTS moneyman.transactions_raw;
DROP TABLE IF EXISTS moneyman.transactions_manual;
DROP TABLE IF EXISTS moneyman.transactions;
DROP TYPE IF EXISTS moneyman.investment_account_type;
DROP TYPE IF EXISTS moneyman.cash_flow_type;
DROP SCHEMA IF EXISTS moneyman;
