\restrict dbmate

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: moneyman; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA moneyman;


--
-- Name: cash_flow_type; Type: TYPE; Schema: moneyman; Owner: -
--

CREATE TYPE moneyman.cash_flow_type AS ENUM (
    'salary',
    'other_income',
    'expense',
    'savings',
    'internal_transfer'
);


--
-- Name: investment_account_type; Type: TYPE; Schema: moneyman; Owner: -
--

CREATE TYPE moneyman.investment_account_type AS ENUM (
    'חשבון השקעות פרטי',
    'קרן השתלמות',
    'פק"מ',
    'קרן כספית',
    'קרן פנסיה מקיפה',
    'קרן פנסיה משלימה',
    'ביטוח מנהלים',
    'קופת גמל',
    'עובר ושב',
    'חסכון לכל ילד',
    'קופת גמל להשקעה'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: business_descriptions; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.business_descriptions (
    id integer NOT NULL,
    description character varying
);


--
-- Name: business_transaction_mappings; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.business_transaction_mappings (
    unique_id text NOT NULL,
    business_descriptions_id integer
);


--
-- Name: transactions; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.transactions (
    unique_id text NOT NULL,
    company_id text NOT NULL,
    account text NOT NULL,
    status text NOT NULL,
    activity_date date NOT NULL,
    charged_amount numeric NOT NULL,
    charged_currency text,
    original_amount numeric,
    original_currency text,
    description text,
    memo text,
    identifier text,
    installments jsonb,
    raw jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: transactions_manual; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.transactions_manual (
    unique_id text NOT NULL,
    account text,
    activity_date date,
    description text,
    original_amount numeric,
    original_currency text,
    charged_amount numeric,
    charged_currency text,
    identifier text,
    additional_info text,
    charged_date timestamp without time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    show_in_transactions boolean DEFAULT true,
    cash_flow_type moneyman.cash_flow_type DEFAULT 'expense'::moneyman.cash_flow_type
);


--
-- Name: combined_transactions; Type: VIEW; Schema: moneyman; Owner: -
--

CREATE VIEW moneyman.combined_transactions AS
 SELECT t.unique_id,
    t.company_id,
    t.account,
    t.status,
    t.activity_date,
    t.charged_amount,
    t.charged_currency,
    t.original_amount,
    t.original_currency,
    t.description,
    t.memo,
    t.identifier,
    t.installments,
    t.raw,
    t.created_at,
    t.updated_at
   FROM moneyman.transactions t
UNION
 SELECT tm.unique_id,
    NULL::text AS company_id,
    tm.account,
    NULL::text AS status,
    tm.activity_date,
    (('-1'::integer)::numeric * tm.charged_amount) AS charged_amount,
    tm.charged_currency,
    tm.original_amount,
    tm.original_currency,
    tm.description,
    NULL::text AS memo,
    tm.identifier,
    NULL::jsonb AS installments,
    NULL::jsonb AS raw,
    tm.created_at,
    tm.updated_at
   FROM moneyman.transactions_manual tm
  WHERE (tm.show_in_transactions IS TRUE);


--
-- Name: description_to_category; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.description_to_category (
    id integer NOT NULL,
    description text,
    category text,
    subcategory text
);


--
-- Name: description_to_category_id_seq; Type: SEQUENCE; Schema: moneyman; Owner: -
--

ALTER TABLE moneyman.description_to_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneyman.description_to_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: investment_accounts; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.investment_accounts (
    id integer NOT NULL,
    person text NOT NULL,
    company text NOT NULL,
    account_type moneyman.investment_account_type NOT NULL,
    account_type_category text,
    is_active boolean DEFAULT true NOT NULL,
    is_pension boolean DEFAULT false NOT NULL,
    deposit_management_fees numeric,
    acc_management_fees numeric,
    investment_track text,
    monthly_deposit numeric,
    account_number text
);


--
-- Name: investment_accounts_id_seq; Type: SEQUENCE; Schema: moneyman; Owner: -
--

CREATE SEQUENCE moneyman.investment_accounts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: investment_accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: moneyman; Owner: -
--

ALTER SEQUENCE moneyman.investment_accounts_id_seq OWNED BY moneyman.investment_accounts.id;


--
-- Name: investment_accounts_tracking; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.investment_accounts_tracking (
    id integer NOT NULL,
    investment_accounts_id integer NOT NULL,
    activity_date date NOT NULL,
    amount numeric NOT NULL
);


--
-- Name: investment_accounts_tracking_id_seq; Type: SEQUENCE; Schema: moneyman; Owner: -
--

CREATE SEQUENCE moneyman.investment_accounts_tracking_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: investment_accounts_tracking_id_seq; Type: SEQUENCE OWNED BY; Schema: moneyman; Owner: -
--

ALTER SEQUENCE moneyman.investment_accounts_tracking_id_seq OWNED BY moneyman.investment_accounts_tracking.id;


--
-- Name: monthly_cash_flow; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.monthly_cash_flow (
    year integer,
    month integer,
    person character varying(50),
    account character varying(50),
    income numeric,
    expense numeric,
    money_transferred numeric,
    savings numeric,
    comments text
);


--
-- Name: wolt_transactions_all_info; Type: VIEW; Schema: moneyman; Owner: -
--

CREATE VIEW moneyman.wolt_transactions_all_info AS
 SELECT wtm.unique_id,
    wtm.business_descriptions_id AS wolt_descriptions_id,
    wd.description AS mapped_description
   FROM (moneyman.business_transaction_mappings wtm
     LEFT JOIN moneyman.business_descriptions wd ON ((wtm.business_descriptions_id = wd.id)));


--
-- Name: processed_transcations_with_categories; Type: VIEW; Schema: moneyman; Owner: -
--

CREATE VIEW moneyman.processed_transcations_with_categories AS
 SELECT t.unique_id,
    t.company_id,
    t.account,
    t.status,
    t.activity_date,
    (('-1'::integer)::numeric * t.charged_amount) AS charged_amount,
    t.charged_amount AS orignial_charged_amount,
    t.charged_currency,
    t.original_amount,
    t.original_currency,
    t.description,
    COALESCE(w.mapped_description, (t.description)::character varying) AS processed_description,
    dtc.category,
    dtc.subcategory,
    t.memo,
    t.identifier,
    t.installments,
    t.created_at,
    t.updated_at
   FROM ((moneyman.combined_transactions t
     LEFT JOIN moneyman.wolt_transactions_all_info w ON ((t.unique_id = w.unique_id)))
     LEFT JOIN moneyman.description_to_category dtc ON (((COALESCE(w.mapped_description, (t.description)::character varying))::text = dtc.description)));


--
-- Name: transactions_raw; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.transactions_raw (
    id bigint NOT NULL,
    raw jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: transactions_raw_id_seq; Type: SEQUENCE; Schema: moneyman; Owner: -
--

CREATE SEQUENCE moneyman.transactions_raw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: transactions_raw_id_seq; Type: SEQUENCE OWNED BY; Schema: moneyman; Owner: -
--

ALTER SEQUENCE moneyman.transactions_raw_id_seq OWNED BY moneyman.transactions_raw.id;


--
-- Name: wolt_descriptions_id_seq; Type: SEQUENCE; Schema: moneyman; Owner: -
--

ALTER TABLE moneyman.business_descriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME moneyman.wolt_descriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_settings; Type: TABLE; Schema: moneyman; Owner: -
--

CREATE TABLE moneyman.app_settings (
    id integer DEFAULT 1 NOT NULL,
    data jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT app_settings_pkey PRIMARY KEY (id),
    CONSTRAINT app_settings_id_check CHECK ((id = 1))
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: investment_accounts id; Type: DEFAULT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.investment_accounts ALTER COLUMN id SET DEFAULT nextval('moneyman.investment_accounts_id_seq'::regclass);


--
-- Name: investment_accounts_tracking id; Type: DEFAULT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.investment_accounts_tracking ALTER COLUMN id SET DEFAULT nextval('moneyman.investment_accounts_tracking_id_seq'::regclass);


--
-- Name: transactions_raw id; Type: DEFAULT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.transactions_raw ALTER COLUMN id SET DEFAULT nextval('moneyman.transactions_raw_id_seq'::regclass);


--
-- Name: description_to_category description_to_category_pkey; Type: CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.description_to_category
    ADD CONSTRAINT description_to_category_pkey PRIMARY KEY (id);


--
-- Name: investment_accounts investment_accounts_pkey; Type: CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.investment_accounts
    ADD CONSTRAINT investment_accounts_pkey PRIMARY KEY (id);


--
-- Name: investment_accounts_tracking investment_accounts_tracking_pkey; Type: CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.investment_accounts_tracking
    ADD CONSTRAINT investment_accounts_tracking_pkey PRIMARY KEY (id);


--
-- Name: transactions_manual transactions_manual_pk; Type: CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.transactions_manual
    ADD CONSTRAINT transactions_manual_pk PRIMARY KEY (unique_id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (unique_id);


--
-- Name: transactions_raw transactions_raw_pkey; Type: CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.transactions_raw
    ADD CONSTRAINT transactions_raw_pkey PRIMARY KEY (id);


--
-- Name: business_descriptions wolt_descriptions_pk; Type: CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.business_descriptions
    ADD CONSTRAINT wolt_descriptions_pk PRIMARY KEY (id);


--
-- Name: business_transaction_mappings wolt_transactions_mappings_pk; Type: CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.business_transaction_mappings
    ADD CONSTRAINT wolt_transactions_mappings_pk PRIMARY KEY (unique_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: transactions_company_account_date_idx; Type: INDEX; Schema: moneyman; Owner: -
--

CREATE INDEX transactions_company_account_date_idx ON moneyman.transactions USING btree (company_id, account, activity_date);


--
-- Name: investment_accounts_tracking investment_accounts_tracking_investment_accounts_id_fkey; Type: FK CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.investment_accounts_tracking
    ADD CONSTRAINT investment_accounts_tracking_investment_accounts_id_fkey FOREIGN KEY (investment_accounts_id) REFERENCES moneyman.investment_accounts(id);


--
-- Name: business_transaction_mappings wolt_transactions_mappings_wolt_descriptions_fk; Type: FK CONSTRAINT; Schema: moneyman; Owner: -
--

ALTER TABLE ONLY moneyman.business_transaction_mappings
    ADD CONSTRAINT wolt_transactions_mappings_wolt_descriptions_fk FOREIGN KEY (business_descriptions_id) REFERENCES moneyman.business_descriptions(id);


--
-- PostgreSQL database dump complete
--

\unrestrict dbmate


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20260417000000'),
    ('20260522000000');
